version: '3'
services:
    orderdb:
        build: 
         context: . 
         dockerfile: DBDockerfile   
        volumes:
            - postgresdb:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        ports:
            - '5432:5432'
        healthcheck:
            test: [CMD-SHELL, 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - samplenet

    rabbitmq:
        image: 'rabbitmq:3.5.3-management'
        container_name: rabbitmq1
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - samplenet


networks:
   samplenet:
volumes:
    postgresdb: {}

